Repository NUS-PocketShop/PocketShop, pull requests merged in 2022-03, with the labels that each got.

#15 Backend
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/AuthAdapter.swift
  PocketShop/Database/Authentication/AuthManager.swift
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/FirebaseManager.swift
  PocketShop/Database/RealtimeDatabase/DBOrders.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DBShop.swift
  PocketShop/Database/RealtimeDatabase/DBStorage.swift
  PocketShop/Database/RealtimeDatabase/DBUsers.swift
  PocketShop/Database/RealtimeDatabase/DatabaseError.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Database/Schema/OrderProductSchema.swift
  PocketShop/Database/Schema/OrderSchema.swift
  PocketShop/Database/Schema/ProductSchema.swift
  PocketShop/Database/Schema/ShopSchema.swift
  PocketShop/Model/Customer.swift
  PocketShop/Model/Order.swift
  PocketShop/Model/OrderProduct.swift
  PocketShop/Model/OrderStatus.swift
  PocketShop/Model/Product.swift
  PocketShop/Model/Shop.swift
  PocketShop/Model/User.swift
  PocketShop/Model/Vendor.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/LoginViewModel.swift
  PocketShop/ViewModels/RegisterViewModel.swift
  PocketShop/Views/CommonViews/MainViewRouter.swift
Labels: sprint1

#16 Allow registration and login for vendor accounts
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/ContentView.swift
  PocketShop/Core/Components/PSRadioButtonGroup.swift
  PocketShop/Core/Components/PSSearchBarView.swift
  PocketShop/Database/RealtimeDatabase/DBOrders.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DBShop.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/LoginViewModel.swift
  PocketShop/ViewModels/RegisterViewModel.swift
  PocketShop/Views/CommonViews/MainViewRouter.swift
  PocketShop/Views/CommonViews/RegisterScreen.swift
  PocketShop/Views/CommonViews/ShopProfileScreen.swift
  PocketShop/Views/CommonViews/ShopRootView.swift
  PocketShop/Views/CommonViews/ShopViewRouter.swift
  PocketShop/Views/CustomerViews/CustomerHomeScreen.swift
Labels: sprint1

#7 Order Screen
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Core/Components/RingView.swift
  PocketShop/Core/Constants/Color+PocketShop.swift
  PocketShop/Core/Resources/Assets.xcassets/Colors/Success.colorset/Contents.json
  PocketShop/Views/CustomerViews/CustomerOrderScreen.swift
  PocketShop/Views/CustomerViews/CustomerProfileScreen.swift
  PocketShop/Views/CustomerViews/CustomerRootView.swift
Labels: sprint1

#17 Add shops and associated products to Customer view
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/ContentView.swift
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/Contents.json
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/cc.imageset/Contents.json
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/cc.imageset/cc.jpeg
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/gc.imageset/Contents.json
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/gc.imageset/gc.png
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/mcd.imageset/Contents.json
  PocketShop/Core/Resources/Assets.xcassets/Images/Shops/mcd.imageset/mcd.jpeg
  PocketShop/Core/Utilities/ImageLoader.swift
  PocketShop/Core/Utilities/URLImage.swift
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBOrders.swift
  PocketShop/Database/RealtimeDatabase/DBStorage.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Images/Shops/cc.jpeg
  PocketShop/Images/Shops/gc.png
  PocketShop/Images/Shops/mcd.jpeg
  PocketShop/Model/Shop.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/Views/CustomerViews/CustomerHomeScreen.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/CustomerViews/ProductListView.swift
  PocketShop/Views/CustomerViews/ProductSummaryView.swift
  PocketShop/Views/CustomerViews/ProductView.swift
  PocketShop/Views/CustomerViews/ProductsScrollView.swift
  PocketShop/Views/CustomerViews/ShopSummaryView.swift
  PocketShop/Views/CustomerViews/ShopsScrollView.swift
Labels: sprint1

#23 Create new shop
  EditShopDetailsScreen.swift
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Core/Components/PSButton.swift
  PocketShop/Core/Components/PSImagePicker.swift
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBShop.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Model/Shop.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/LoginViewModel.swift
  PocketShop/ViewModels/RegisterViewModel.swift
  PocketShop/ViewModels/ShopInfoView.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CommonViews/ShopProfileScreen.swift
  PocketShop/Views/CommonViews/ShopRootView.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/CustomerViews/ShopSummaryView.swift
  ShopHomeScreen.swift
Labels: feature, sprint1, work in progress

#24 Adding products to shop view (with firebase integration)
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/ShopViews/ShopProductFormView.swift
  PocketShop/ShopViews/ShopProductsView.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/CustomerViews/ProductListView.swift
  PocketShop/Views/CustomerViews/ProductOrderBar.swift
  ShopHomeScreen.swift
Labels: feature, sprint1, ready to merge

#29 Cleanup View Model
  PocketShop/ContentView.swift
  PocketShop/Core/Components/PSImagePicker.swift
  PocketShop/ShopViews/ShopProductFormView.swift
  PocketShop/ShopViews/ShopProductsView.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CommonViews/LoginScreen.swift
  PocketShop/Views/CommonViews/RegisterScreen.swift
  PocketShop/Views/CustomerViews/CustomerHomeScreen.swift
  PocketShop/Views/CustomerViews/CustomerOrderScreen.swift
  PocketShop/Views/CustomerViews/CustomerRootView.swift
Labels: bug, sprint2, ready to merge
