Repository NUS-PocketShop/PocketShop, pull requests merged in 2022-04, with the labels that each got.

#42 Improve edit products UX
  PocketShop/Database/RealtimeDatabase/DBUsers.swift
  PocketShop/Database/Schema/ProductSchema.swift
  PocketShop/Database/Schema/ShopSchema.swift
  PocketShop/Model/Product.swift
  PocketShop/ShopViews/ShopOrderScreen.swift
  PocketShop/ShopViews/ShopProductEditFormView.swift
  PocketShop/ShopViews/ShopProductFormView.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/OrderViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CustomerOrderScreen.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/CustomerViews/ProductOrderBar.swift
Labels: sprint2, ready to merge

#48 Improve app UI
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Core/Constants/Constants.swift
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  PocketShop/Core/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  PocketShop/Core/Resources/Assets.xcassets/Images/pocketshop-round.imageset/Contents.json
  PocketShop/Core/Resources/Assets.xcassets/Images/pocketshop-round.imageset/pocketshop-round.png
  PocketShop/Database/Schema/OrderProductSchema.swift
  PocketShop/Model/OrderProduct.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/Views/CommonViews/LoginScreen.swift
  PocketShop/Views/CommonViews/RegisterScreen.swift
  PocketShop/Views/CommonViews/ShopProfileScreen.swift
  PocketShop/Views/CustomerViews/CustomerCartScreen.swift
  PocketShop/Views/CustomerViews/CustomerProfileScreen.swift
  PocketShop/Views/CustomerViews/CustomerRootView.swift
  PocketShop/Views/CustomerViews/ProductOrderBar.swift
Labels: enhancement, sprint2, ready to merge

#49 Fix schemas using arrays
  PocketShop/Database/Schema/CartProductSchema.swift
  PocketShop/Database/Schema/ProductSchema.swift
  PocketShop/Database/Schema/ShopSchema.swift
Labels: ready to merge

#47 Make Product Category Views
  EditShopDetailsScreen.swift
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DBShop.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Model/Order.swift
  PocketShop/ShopViews/ShopProductFormView.swift
  PocketShop/ViewModels/ShopInfoView.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/ShopViews/ShopEditFormView.swift
  PocketShop/Views/ShopViews/ShopFormView.swift
  PocketShop/Views/ShopViews/ShopHomeScreen.swift
  PocketShop/Views/ShopViews/ShopOrderScreen.swift
  PocketShop/Views/ShopViews/ShopProductEditFormView.swift
  PocketShop/Views/ShopViews/ShopProductFormView.swift
  PocketShop/Views/ShopViews/ShopProductsView.swift
Labels: sprint2, ready to merge

#45 Feature: Open & Close Shops
  PocketShop/Database/RealtimeDatabase/DBCart.swift
  PocketShop/Database/Schema/CartProductSchema.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CommonViews/ShopProfileScreen.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/CustomerViews/ShopsScrollView.swift
  PocketShop/Views/ShopViews/ShopProductFormView.swift
  PocketShop/Views/ShopViews/ShopProductsView.swift
Labels: feature, sprint2, ready to merge

#59 Enhance radio button
  PocketShop/Core/Components/PSRadioButtonGroup.swift
  PocketShop/Database/RealtimeDatabase/DBOrders.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/Views/CustomerViews/CustomerOrderScreen.swift
  PocketShop/Views/ShopViews/ShopOrderScreen.swift
Labels: enhancement, sprint3, ready to merge

#60 Improve 'Add to Cart' process
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Core/Components/PSBadge.swift
  PocketShop/Views/CustomerViews/CustomerRootView.swift
  PocketShop/Views/CustomerViews/ProductOrderBar.swift
Labels: enhancement, sprint3, ready to merge

#61 Add sprint 3 models
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/Authentication/AuthManager.swift
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBLocation.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DBUsers.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Database/Schema/ProductSchema.swift
  PocketShop/Database/Schema/ShopSchema.swift
  PocketShop/Model/Customer.swift
  PocketShop/Model/Location.swift
  PocketShop/Model/Product.swift
  PocketShop/Model/Shop.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CommonViews/ShopProfileScreen.swift
  PocketShop/Views/ShopViews/ShopEditFormView.swift
  PocketShop/Views/ShopViews/ShopFormView.swift
  PocketShop/Views/ShopViews/ShopProductEditFormView.swift
  PocketShop/Views/ShopViews/ShopProductFormView.swift
Labels: sprint3, ready to merge

#66 Small fix to customer
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/RealtimeDatabase/DBUsers.swift
  PocketShop/Database/Schema/CustomerSchema.swift
Labels: sprint3, ready to merge

#70 Implement product stock status frontend
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/CustomerViews/ProductListView.swift
  PocketShop/Views/CustomerViews/ProductsScrollView.swift
  PocketShop/Views/ShopViews/ShopProductListView.swift
  PocketShop/Views/ShopViews/ShopProductsView.swift
Labels: sprint3, ready to merge

#71 Edit Cart + Fix from Sprint 2
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/OrderViewModel.swift
  PocketShop/Views/CustomerViews/CustomerCartScreen.swift
  PocketShop/Views/CustomerViews/ProductDetailView.swift
  PocketShop/Views/CustomerViews/ProductOrderBar.swift
  PocketShop/Views/ShopViews/ShopOrderScreen.swift
Labels: sprint3, ready to merge

#72 Misc changes
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/Authentication/AuthManager.swift
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBCart.swift
  PocketShop/Database/RealtimeDatabase/DBLocation.swift
  PocketShop/Database/RealtimeDatabase/DBOrders.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DBShop.swift
  PocketShop/Database/RealtimeDatabase/DBStorage.swift
  PocketShop/Database/RealtimeDatabase/DBUsers.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Database/Schema/CartProductSchema.swift
  PocketShop/Database/Schema/CustomerSchema.swift
  PocketShop/Database/Schema/LocationSchema.swift
  PocketShop/Database/Schema/OrderProductSchema.swift
  PocketShop/Database/Schema/OrderSchema.swift
  PocketShop/Database/Schema/ProductSchema.swift
  PocketShop/Database/Schema/ShopSchema.swift
  PocketShop/Database/Schema/VendorSchema.swift
  PocketShop/Model/CartProduct.swift
  PocketShop/Model/Customer.swift
  PocketShop/Model/ID.swift
  PocketShop/Model/Location.swift
  PocketShop/Model/Order.swift
  PocketShop/Model/OrderProduct.swift
  PocketShop/Model/Product.swift
  PocketShop/Model/Shop.swift
  PocketShop/Model/User.swift
  PocketShop/Model/Vendor.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/OrderViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/ProductDetailView.swift
  PocketShop/Views/ShopViews/ShopFormView.swift
  PocketShop/Views/ShopViews/ShopProductFormView.swift
  PocketShop/Views/ShopViews/ShopProfileScreen.swift
Labels: sprint3, ready to merge

#74 Add coupons to model
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBCoupons.swift
  PocketShop/Database/RealtimeDatabase/DBUsers.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Database/Schema/CouponSchema.swift
  PocketShop/Database/Schema/CustomerSchema.swift
  PocketShop/Database/Schema/OrderSchema.swift
  PocketShop/Model/Coupon.swift
  PocketShop/Model/Customer.swift
  PocketShop/Model/Order.swift
  PocketShop/ViewModels/CustomerViewModel+Observers.swift
  PocketShop/ViewModels/CustomerViewModel.swift
Labels: sprint3, ready to merge

#73 UI/UX Improvements
  PocketShop/ViewModels/OrderViewModel.swift
  PocketShop/Views/CustomerViews/ProductListView.swift
  PocketShop/Views/ShopViews/ShopOrderScreen.swift
  PocketShop/Views/ShopViews/ShopProductListView.swift
  PocketShop/Views/ShopViews/ShopProductsView.swift
Labels: enhancement, sprint3, ready to merge

#75 Implement Product Tags
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Core/Components/PSMultiLineTextField.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CustomerLocationView.swift
  PocketShop/Views/ShopViews/ShopFormView.swift
  PocketShop/Views/ShopViews/ShopProductEditFormView.swift
  PocketShop/Views/ShopViews/ShopProductFormView.swift
Labels: sprint3, ready to merge

#77 Add checks to ensure product and shop image size < 5MB
  PocketShop/Database/RealtimeDatabase/DBStorage.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/ShopViews/ShopEditFormView.swift
  PocketShop/Views/ShopViews/ShopFormView.swift
  PocketShop/Views/ShopViews/ShopProductEditFormView.swift
  PocketShop/Views/ShopViews/ShopProductFormView.swift
Labels: sprint3, ready to merge

#78 Implement Rewards and Coupons
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/Database/Schema/OrderSchema.swift
  PocketShop/Model/Coupon.swift
  PocketShop/Model/Order.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CouponListView.swift
  PocketShop/Views/CustomerViews/CouponRedemptionScreen.swift
  PocketShop/Views/CustomerViews/CustomerCartScreen.swift
  PocketShop/Views/CustomerViews/CustomerOrderScreen.swift
  PocketShop/Views/CustomerViews/CustomerProfileScreen.swift
  PocketShop/Views/CustomerViews/DiscountTextView.swift
Labels: sprint3, ready to merge

#79 Implement product and category ordering
  PocketShop/Database/DatabaseAdapter.swift
  PocketShop/Database/RealtimeDatabase/DBProducts.swift
  PocketShop/Database/RealtimeDatabase/DBShop.swift
  PocketShop/Database/RealtimeDatabase/DatabaseManager.swift
  PocketShop/Database/Schema/ProductSchema.swift
  PocketShop/Model/Product.swift
  PocketShop/Model/Shop.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/VendorViewModel.swift
  PocketShop/Views/CustomerViews/CustomerShopView.swift
  PocketShop/Views/ShopViews/Product Forms/ShopProductEditFormView.swift
  PocketShop/Views/ShopViews/Product Forms/ShopProductFormView.swift
  PocketShop/Views/ShopViews/Shop Forms/ShopCreationFormView.swift
  PocketShop/Views/ShopViews/Shop Forms/ShopEditFormView.swift
  PocketShop/Views/ShopViews/ShopProductsView.swift
Labels: sprint3, ready to merge

#80 Remove unused dirs
  PocketShop.xcodeproj/project.pbxproj
  PocketShopTests/PocketShopTests.swift
  PocketShopUITests/PocketShopUITests.swift
  PocketShopUITests/PocketShopUITestsLaunchTests.swift
Labels: sprint3, ready to merge

#81 Remove closed shops' products from ProductsScrollView
  PocketShop/Views/CustomerViews/ProductsScrollView.swift
Labels: sprint3, ready to merge

#82 Clean up files
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/ViewModels/Common/LoginViewModel.swift
  PocketShop/ViewModels/Common/RegisterViewModel.swift
  PocketShop/ViewModels/Customer/CustomerViewModel+CartManagement.swift
  PocketShop/ViewModels/Customer/CustomerViewModel+Favorites.swift
  PocketShop/ViewModels/Customer/CustomerViewModel+Observers.swift
  PocketShop/ViewModels/Customer/CustomerViewModel+Rewards.swift
  PocketShop/ViewModels/Customer/CustomerViewModel.swift
  PocketShop/ViewModels/CustomerViewModel.swift
  PocketShop/ViewModels/Ordering/OrderViewModel.swift
  PocketShop/ViewModels/Vendor/VendorViewModel+Inventory.swift
  PocketShop/ViewModels/Vendor/VendorViewModel.swift
  PocketShop/Views/CustomerViews/Cart/CouponListView.swift
  PocketShop/Views/CustomerViews/Cart/CouponRedemptionScreen.swift
  PocketShop/Views/CustomerViews/Cart/DiscountTextView.swift
  PocketShop/Views/CustomerViews/Cart/ProductOrderBar.swift
  PocketShop/Views/CustomerViews/Favorites/CustomerFavouritesScreen.swift
  PocketShop/Views/CustomerViews/FrontPage/CustomerLocationView.swift
  PocketShop/Views/CustomerViews/FrontPage/CustomerShopView.swift
  PocketShop/Views/CustomerViews/FrontPage/LocationSummaryView.swift
  PocketShop/Views/CustomerViews/FrontPage/LocationsScrollView.swift
  PocketShop/Views/CustomerViews/FrontPage/ProductDetailView.swift
  PocketShop/Views/CustomerViews/FrontPage/ProductListView.swift
  PocketShop/Views/CustomerViews/FrontPage/ProductSummaryView.swift
  PocketShop/Views/CustomerViews/FrontPage/ProductsScrollView.swift
  PocketShop/Views/CustomerViews/FrontPage/ShopListView.swift
  PocketShop/Views/CustomerViews/FrontPage/ShopSummaryView.swift
  PocketShop/Views/CustomerViews/FrontPage/ShopsScrollView.swift
Labels: enhancement, ready to merge

#83 Minor bug fixes
  PocketShop.xcodeproj/project.pbxproj
  PocketShop/ViewModels/Customer/CustomerViewModel.swift
  PocketShop/Views/CustomerViews/CustomerOrderScreen.swift
  PocketShop/Views/CustomerViews/FrontPage/ProductsScrollView.swift
Labels: sprint3, ready to merge

#84 Fix more bugs
  PocketShop/Views/CustomerViews/Cart/ProductOrderBar.swift
  PocketShop/Views/ShopViews/ShopHomeScreen.swift
  PocketShop/Views/ShopViews/ShopProductsView.swift
Labels: bug, enhancement, sprint3, ready to merge
